services:
  stream-vault:
    build: .
    container_name: stream-vault
    ports:
      - "3000:3000"
    env_file: .env
    restart: unless-stopped
    volumes:
      - ./users.json:/app/users.json
      - ./suggestions.json:/app/suggestions.json